import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { setGlobalDispatcher, ProxyAgent } from "undici";
const dispatcher = new ProxyAgent({uri: new URL("https://127.0.0.1:8080").toString() });
setGlobalDispatcher(dispatcher);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
